Feature/app tracking transparency
ringpublishing/RingPublishingGDPR-iOS pull request #9
Opened 2021-02-15 14:13 UTC by adamszeremeta

2021-02-16 08:01 UTC, pkordal requested changes
Trochę tu, trochę tam.

2021-02-16 08:02 UTC, pkordal commented on Changelogs/1.3.0
> +* Module initialization parameters: 'gdprApplies', 'tenantId', 'brandName' moved to 'RingPublishingGDPRConfig' class.
dobra.. obj c.

2021-02-16 08:43 UTC, adamszeremeta commented on RingPublishingGDPR/Classes/Private/AppTrackingTransparencyManager.swift
> +            // This should never happen
wyżej jest identyczny guard, nie ma szans :)

2021-02-16 08:47 UTC, adamszeremeta commented on RingPublishingGDPR/Classes/Private/GDPRManagerDelegate.swift
> +    func gdprManager(_ manager: GDPRManager, isRequestingToOpenUrl url: URL)
w publicznym delegacie jest did, w wewnętrznym is

2021-02-16 08:51 UTC, adamszeremeta commented on RingPublishingGDPR/Classes/Private/GDPRManagerDelegate.swift
> +    /// Manager is requesting to open url selected inside view controller by the user
wyjaśnione - na teraz zostawiamy jak jest, bo osobny delegat ma negatywne konsekwencje także

2021-02-17 09:50 UTC, pkordal commented on RingPublishingGDPR/Classes/Private/GDPRManagerDelegate.swift
> +    /// Manager is informing that user selected on of the options on ATT explaination screen
explanation

2021-02-17 10:02 UTC, pkordal commented on RingPublishingGDPR/Classes/Private/Views/AppTrackingTransparencyView.swift
> +        configureDescriptionText(text, textColor: textColor, uiConfig: uiConfig, desiredFontSize: fontSize - 1)
a może by tak jakoś to w pętli zrobić? że jak się nie mieści to dalej -1 i tak do 3 razy? ;)

2021-02-17 10:17 UTC, pkordal approved these changes

2021-02-18 13:45 UTC, merged